services:


  gomoku:
    build: .
    container_name: gomoku
    volumes:
      - ./file:/usr/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/root/.Xauthority:ro
    environment:
      - DISPLAY=${DISPLAY} 
      - XAUTHORITY=/root/.Xauthority
    networks:
      - gomok
    working_dir: /usr/app
    command: ["tail", "-f", "/dev/null"]
    # command: make all
    # command: ["sh", "-c", "./gomoku"]


networks:
  gomok: