services:


  gomoku:
    build: .
    container_name: gomoku
    volumes:
      - ./file:/usr/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY} 
    networks:
      - gomok
    working_dir: /usr/app
    # command: ["tail", "-f", "/dev/null"]
    # command: make all
    command: ["sh", "-c", "make all && ./gomoku"]


networks:
  gomok: